In [2]:
import pandas as pd
import os
import numpy as np

In [3]:
# Caminhos padrões para os arquivos e pastas
caminho_raw = "../dados/raw"
caminho_processed = "../dados/processed"
caminho_gold = "../dados/gold"

In [4]:
# Visualização das colunas de dados 'float' para somente 2 casas decimais
pd.set_option('display.float_format', '{:,.2f}'.format)

In [9]:
# leitura dos dados de basileia
df_basileia = pd.read_parquet(os.path.join(caminho_raw,'basileia_raw.parquet'))

# Renomeação das colunas para facilitar visualização e direcionamentos das melhores práticos python

df_basileia

,Instituição,Código,TCB,TD,TC,Cidade,UF,Data,Índice de Basileia (n) = (e) / (j)
0,ITAU - PRUDENCIAL,"1,000,080,099.00",b1,C,2.00,SAO PAULO,SP,03/2023,None
1,BB - PRUDENCIAL,"1,000,080,329.00",b1,C,1.00,BRASILIA,DF,03/2023,None
2,BRADESCO - PRUDENCIAL,"1,000,080,075.00",b1,C,2.00,OSASCO,SP,03/2023,None
3,CAIXA ECONÔMICA FEDERAL - PRUDENCIAL,"1,000,080,738.00",b1,C,1.00,BRASILIA,DF,03/2023,None
4,SANTANDER - PRUDENCIAL,"1,000,080,185.00",b1,C,2.00,SAO PAULO,SP,03/2023,None
...,...,...,...,...,...,...,...,...,...
14759,ISTPAY IP - PRUDENCIAL,"1,000,087,597.00",n4,I,2.00,BELO HORIZONTE,MG,12/2024,NI%
14760,99PAY IP - PRUDENCIAL,"1,000,087,793.00",n1,C,3.00,SAO PAULO,SP,12/2024,NI%
14761,DELTA GLOBAL SCD - PRUDENCIAL,"1,000,087,937.00",n1,I,2.00,SAO PAULO,SP,12/2024,NI%
14762,LP DO BRASIL IP - PRUDENCIAL,"1,000,088,053.00",n4,I,3.00,CAMPINAS,SP,12/2024,NI%
14763,CALCARD IP - PRUDENCIAL,"1,000,088,170.00",n1,C,2.00,PALHOCA,SC,12/2024,NI%

In [6]:
# leitura dos dados do dre
df_dre = pd.read_parquet(os.path.join(caminho_raw,'dre_raw.parquet'))

# Renomeação das colunas para facilitar visualização e direcionamentos das melhores práticos python
colunas_renomeadas = {
    'Instituição': 'instituicao',
    'Conglomerado Prudencial': 'conglomerado_prudencial',
    'Código': 'codigo_bacen',
    'TCB': 'tcb',
    'TC': 'tc',
    'TI': 'ti',
    'Cidade': 'cidade',
    'UF': 'uf',
    'Data': 'data_base',
    'Resultado de Intermediação Financeira (k) = (a) + (b) + (c) + (d) + (e) + (f) + (g) + (h) + (i) + (j)': 'resultado_intermediacao',
    'Resultado com Transações de Pagamento (l)': 'resultado_pagamentos',
    'Outras Receitas / Despesas (w)= (m) + (n) + (o) +  (p) + (q) + (r) + (s) + (t) + (u) + (v)': 'outras_receitas_despesas',
    'Resultado antes da Tributação e Participações (x) = (k) + (l) + (w)': 'resultado_antes_impostos', # LAIR
    'Imposto de Renda e Contribuição Social (y)': 'impostos_ir_csll',
    'Participações no Lucro (z)': 'participacoes_lucro',
    'Lucro Líquido (aa) = (x) + (y) + (z)': 'lucro_liquido'
}

df_dre = df_dre.rename(columns=colunas_renomeadas)

# Transformação dos tipos de dados (float, categoria, string, integer, date_time). Além de tranformar valores não informados (NI) para zero (0), para deixar no formato adequado.
colunas_para_float = [
    'resultado_intermediacao',
    'resultado_pagamentos',
    'outras_receitas_despesas',
    'impostos_ir_csll',
    'participacoes_lucro',
    'resultado_antes_impostos',
    'lucro_liquido'
]

cols_id = ['codigo_bacen', 'tc', 'ti']

cols_categoria = ['uf', 'tcb']

cols_str = ['instituicao','cidade']

for col in colunas_para_float:
    df_dre[col] = df_dre[col].astype(str).str.replace('.', '', regex=False)
    df_dre[col] = pd.to_numeric(df_dre[col], errors='coerce')

for col in cols_id:
    df_dre[col] = pd.to_numeric(df_dre[col], errors='coerce').astype('Int64')

for col in cols_categoria:
    df_dre[col] = df_dre[col].astype('category')

for col in cols_str:
    df_dre[col] = df_dre[col].astype('string')

df_dre['data_base'] = pd.to_datetime(df_dre['data_base'], format='%m/%Y', errors='coerce')

df_dre = df_dre.replace(['NI', 'Ni', 'ni'], np.nan)

# Salvar arquivo DRE transformado
df_dre.to_parquet(os.path.join(caminho_processed,"dre_processed.parquet"))

df_dre.info()
df_dre.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17170 entries, 0 to 17169
Data columns (total 29 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   instituicao                                  17170 non-null  string
 1   codigo_bacen                                 17170 non-null  Int64
 2   conglomerado_prudencial                      8373 non-null   object
 3   tcb                                          17170 non-null  category
 4   tc                                           17170 non-null  Int64
 5   ti                                           17170 non-null  Int64
 6   cidade                                       17170 non-null  string
 7   uf                                           17170 non-null  category
 8   data_base                                    17170 non-null  datetime64[ns]
 9   Rendas de Títulos e Valores Mobiliários (b)  17042 non-null  object
 10  Rendas de Operações de Crédito (c)           17042 non-null  object
 11  Resultado com Perda Esperada (f)             17042 non-null  object
 12  Despesa de Juros com Captações (g1)          17042 non-null  object
 13  Resultado com Derivativos (i)                17042 non-null  object
 14  resultado_intermediacao                      17042 non-null  float64
 15  resultado_pagamentos                         17086 non-null  float64
 16  Rendas de Tarifas Bancárias (m)              17042 non-null  object
 17  Outras Rendas de Prestação de Serviços (n)   17042 non-null  object
 18  Despesas de Pessoal (o)                      17042 non-null  object
 19  Despesas Administrativas (p)                 17042 non-null  object
 20  Despesas Tributárias (s)                     17042 non-null  object
 21  Resultado de Participações (t)               17042 non-null  object
 22  Outras Receitas (u)                          17042 non-null  object
 23  Outras Despesas (v)                          17042 non-null  object
 24  outras_receitas_despesas                     17042 non-null  float64
 25  resultado_antes_impostos                     17042 non-null  float64
 26  impostos_ir_csll                             17042 non-null  float64
 27  participacoes_lucro                          17042 non-null  float64
 28  lucro_liquido                                17042 non-null  float64
dtypes: Int64(3), category(2), datetime64[ns](1), float64(7), object(14), string(2)
memory usage: 3.6+ MB

,instituicao,codigo_bacen,conglomerado_prudencial,tcb,tc,ti,cidade,uf,data_base,Rendas de Títulos e Valores Mobiliários (b),...,Despesas Administrativas (p),Despesas Tributárias (s),Resultado de Participações (t),Outras Receitas (u),Outras Despesas (v),outras_receitas_despesas,resultado_antes_impostos,impostos_ir_csll,participacoes_lucro,lucro_liquido
0,BANCO DO BRASIL S.A.,0,BB - PRUDENCIAL,b1,1,1,BRASILIA,DF,2022-12-01,58.596.285,...,-5.237.470,-2.451.338,8.284.131,10.796.191,-7.750.692,"3,317,134.00","21,753,526.00","-2,982,566.00","-2,132,589.00","16,638,371.00"
1,CAIXA ECONOMICA FEDERAL,360305,CAIXA ECONÔMICA FEDERAL - PRUDENCIAL,b1,1,6,BRASILIA,DF,2022-12-01,24.831.667,...,-5.973.955,-1.999.036,2.041.360,6.311.604,-11.957.151,"-13,944,940.00","5,582,178.00","971,396.00","-1,060,139.00","5,493,435.00"
2,ITAÚ UNIBANCO S.A.,60701190,ITAU - PRUDENCIAL,b1,2,8,SAO PAULO,SP,2022-12-01,43.986.868,...,-8.321.352,-1.936.088,8.502.395,8.463.879,-6.389.630,"2,758,344.00","18,299,359.00","1,334,900.00","-3,690,333.00","15,943,927.00"
3,BANCO BRADESCO S.A.,60746948,BRADESCO - PRUDENCIAL,b1,2,8,OSASCO,SP,2022-12-01,35.028.544,...,-9.713.000,-2.397.203,7.669.313,6.842.800,-7.288.312,"-3,427,060.00","2,897,870.00","3,749,785.00",0.00,"6,647,656.00"
4,BANCO SANTANDER (BRASIL) S.A.,90400888,SANTANDER - PRUDENCIAL,b1,3,8,SAO PAULO,SP,2022-12-01,16.816.762,...,-6.080.297,-1.577.849,4.935.164,13.118.048,-13.289.969,"1,739,955.00","2,602,071.00","2,970,185.00","-990,117.00","4,582,139.00"

In [7]:
# leitura dos dados do RESUMO
df_resumo = pd.read_parquet(os.path.join(caminho_raw, "resumo_raw.parquet"))

# Renomeação das colunas para facilitar visualização e direcionamentos das melhores práticos python
colunas_para_renomear = {
    'Instituição': 'instituicao',
    'Código': 'codigo_bacen',
    'Conglomerado Prudencial': 'conglomerado',
    'TCB': 'tcb',
    'TC': 'tc',
    'TI': 'ti',
    'Cidade': 'cidade',
    'UF': 'uf',
    'Data': 'data_base',
    'Ativo Total' : 'ativo_total',
    'Captações' : 'captacoes',
    'Patrimônio Líquido' : 'patrimonio_liquido',
    'Lucro Líquido' : 'lucro_liquido',
    'Número de Agências' : 'numero_agencias',
    'Número de Postos de Atendimento' : 'numero_postos_atendimento',
    'Carteira de Crédito' : 'carteira_credito',
    'Passivo Exigível' : 'passivel_exigivel'
}

df_resumo = df_resumo.rename(columns=colunas_para_renomear)

# Transformação dos tipos de dados (float, categoria, string, integer, date_time). Além de tranformar valores não informados (NI) para zero (0), para deixar no formato adequado.
colunas_float = [
    'ativo_total',
    'captacoes',
    'patrimonio_liquido',
    'lucro_liquido',
    'numero_agencias',
    'numero_postos_atendimento',
    'carteira_credito',
    'passivel_exigivel'
]

cols_id = ['codigo_bacen', 'tc', 'ti']

cols_categoria = ['uf', 'tcb','conglomerado']

cols_str = ['instituicao','cidade']

for col in colunas_float:
    df_resumo[col] = df_resumo[col].astype(str).str.replace('.', '', regex=False)
    df_resumo[col] = pd.to_numeric(df_resumo[col], errors='coerce')

for col in cols_id:
    df_resumo[col] = pd.to_numeric(df_resumo[col], errors='coerce').astype('Int64')

for col in cols_categoria:
    df_resumo[col] = df_resumo[col].astype('category')

for col in cols_str:
    df_resumo[col] = df_resumo[col].astype('string')

df_resumo['data_base'] = pd.to_datetime(df_resumo['data_base'], format='%m/%Y', errors='coerce')

df_resumo = df_resumo.replace(['NI', 'Ni', 'ni'], np.nan)

df_resumo = df_resumo.set_index('data_base')

# Salvar arquivo DRE transformado
df_resumo.to_parquet(os.path.join(caminho_processed, "resumo_processed.parquet"))

df_resumo.info()
df_resumo.head()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 17170 entries, 2022-12-01 to 2025-06-01
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   instituicao                17170 non-null  string
 1   codigo_bacen               17170 non-null  Int64
 2   conglomerado               8373 non-null   category
 3   tcb                        17170 non-null  category
 4   tc                         17170 non-null  Int64
 5   ti                         17170 non-null  Int64
 6   cidade                     17170 non-null  string
 7   uf                         17170 non-null  category
 8   ativo_total                17042 non-null  float64
 9   captacoes                  17042 non-null  float64
 10  patrimonio_liquido         17042 non-null  float64
 11  lucro_liquido              17042 non-null  float64
 12  numero_agencias            17170 non-null  int64
 13  numero_postos_atendimento  17170 non-null  int64
 14  carteira_credito           17042 non-null  float64
 15  passivel_exigivel          17042 non-null  float64
dtypes: Int64(3), category(3), float64(6), int64(2), string(2)
memory usage: 2.0 MB

,instituicao,codigo_bacen,conglomerado,tcb,tc,ti,cidade,uf,ativo_total,captacoes,patrimonio_liquido,lucro_liquido,numero_agencias,numero_postos_atendimento,carteira_credito,passivel_exigivel
data_base,,,,,,,,,,,,,,,,
2022-12-01,BANCO DO BRASIL S.A.,0,BB - PRUDENCIAL,b1,1,1,BRASILIA,DF,"1,927,604,248.00","1,551,106,608.00","153,546,924.00","16,638,371.00",3985,604,"853,636,272.00","1,774,057,324.00"
2022-12-01,ITAÚ UNIBANCO S.A.,60701190,ITAU - PRUDENCIAL,b1,2,8,SAO PAULO,SP,"1,621,520,167.00","1,323,163,687.00","129,564,325.00","15,943,927.00",2584,1003,"406,186,786.00","1,491,955,842.00"
2022-12-01,CAIXA ECONOMICA FEDERAL,360305,CAIXA ECONÔMICA FEDERAL - PRUDENCIAL,b1,1,6,BRASILIA,DF,"1,585,795,602.00","1,315,128,052.00","84,813,538.00","5,493,435.00",3373,937,"1,012,344,567.00","1,500,982,064.00"
2022-12-01,BANCO BRADESCO S.A.,60746948,BRADESCO - PRUDENCIAL,b1,2,8,OSASCO,SP,"1,489,174,462.00","1,147,488,387.00","154,263,223.00","6,647,656.00",2865,1277,"543,700,762.00","1,334,911,238.00"
2022-12-01,BANCO SANTANDER (BRASIL) S.A.,90400888,SANTANDER - PRUDENCIAL,b1,3,8,SAO PAULO,SP,"986,299,576.00","722,481,108.00","81,076,905.00","4,582,139.00",2573,1557,"341,933,356.00","905,222,672.00"

In [8]:
# Criação de um novo dataframe 'analitico', com a junção de resumo e dre, facilitando visualização, análise e correlação.
df_analitico = pd.merge(
    df_resumo, 
    df_dre, 
    on=['codigo_bacen', 'data_base'], 
    how='inner',
    suffixes=('', '_dre') # indicar as colunas que estão em ambos dataframes, colocando o sufixo do df_dre
)

# Removendo colunas que ficaram duplicadas.
colunas_remover = [c for c in df_analitico.columns if '_dre' in c]
df_analitico = df_analitico.drop(columns=colunas_remover)

# Salvar dataframe gold, no qual utilizaremos para análises e novas features.
df_analitico.to_parquet(os.path.join(caminho_gold, "df_gold.parquet"))